// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file main.proto (package proto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListAccountReq, ListAccountResp } from "./main_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.Main
 */
export const Main = {
  typeName: "proto.Main",
  methods: {
    /**
     * @generated from rpc proto.Main.ListAccount
     */
    listAccount: {
      name: "ListAccount",
      I: ListAccountReq,
      O: ListAccountResp,
      kind: MethodKind.Unary,
    },
  }
} as const;

