// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStore = "Stores"

// Store mapped from table <Stores>
type Store struct {
	ID        int32     `gorm:"column:ID;primaryKey" json:"ID"`
	CreatedAt time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
	UpdatedAt time.Time `gorm:"column:UpdatedAt" json:"UpdatedAt"`
	DeletedAt time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
	Name      string    `gorm:"column:Name" json:"Name"`
	ParentID  int32     `gorm:"column:ParentID" json:"ParentID"`
}

// TableName Store's table name
func (*Store) TableName() string {
	return TableNameStore
}
