// @generated by protoc-gen-es v1.10.0
// @generated from file main.proto (package proto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message proto.ListAccountReq
 */
export declare class ListAccountReq extends Message<ListAccountReq> {
  constructor(data?: PartialMessage<ListAccountReq>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "proto.ListAccountReq";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListAccountReq;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListAccountReq;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListAccountReq;

  static equals(a: ListAccountReq | PlainMessage<ListAccountReq> | undefined, b: ListAccountReq | PlainMessage<ListAccountReq> | undefined): boolean;
}

/**
 * @generated from message proto.ListAccountResp
 */
export declare class ListAccountResp extends Message<ListAccountResp> {
  /**
   * @generated from field: repeated proto.Account List = 1;
   */
  List: Account[];

  /**
   * @generated from field: string Total = 2;
   */
  Total: string;

  constructor(data?: PartialMessage<ListAccountResp>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "proto.ListAccountResp";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListAccountResp;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListAccountResp;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListAccountResp;

  static equals(a: ListAccountResp | PlainMessage<ListAccountResp> | undefined, b: ListAccountResp | PlainMessage<ListAccountResp> | undefined): boolean;
}

/**
 * @generated from message proto.Account
 */
export declare class Account extends Message<Account> {
  /**
   * @generated from field: string UserName = 1;
   */
  UserName: string;

  /**
   * @generated from field: string DisplayName = 2;
   */
  DisplayName: string;

  /**
   * @generated from field: int32 State = 3;
   */
  State: number;

  constructor(data?: PartialMessage<Account>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "proto.Account";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Account;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Account;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Account;

  static equals(a: Account | PlainMessage<Account> | undefined, b: Account | PlainMessage<Account> | undefined): boolean;
}

