// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccount = "Accounts"

// Account mapped from table <Accounts>
type Account struct {
	ID          int32     `gorm:"column:ID;primaryKey" json:"ID"`
	CreatedAt   time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
	UpdatedAt   time.Time `gorm:"column:UpdatedAt" json:"UpdatedAt"`
	DeletedAt   time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
	UserName    string    `gorm:"column:UserName;not null" json:"UserName"`
	State       int32     `gorm:"column:State;not null;default:1" json:"State"`
	HashPass    []byte    `gorm:"column:HashPass;not null" json:"HashPass"`
	Salt        []byte    `gorm:"column:Salt;not null" json:"Salt"`
	DisplayName string    `gorm:"column:DisplayName;not null" json:"DisplayName"`
	RoleID      int32     `gorm:"column:RoleID" json:"RoleID"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
