// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "Roles"

// Role mapped from table <Roles>
type Role struct {
	ID                int32     `gorm:"column:ID;primaryKey" json:"ID"`
	CreatedAt         time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
	UpdatedAt         time.Time `gorm:"column:UpdatedAt" json:"UpdatedAt"`
	DeletedAt         time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
	Name              string    `gorm:"column:Name;not null" json:"Name"`
	PageRoleCreate    int32     `gorm:"column:PageRoleCreate;not null;default:false" json:"PageRoleCreate"`
	PageRoleRead      int32     `gorm:"column:PageRoleRead;not null;default:false" json:"PageRoleRead"`
	PageRoleUpdate    int32     `gorm:"column:PageRoleUpdate;not null;default:false" json:"PageRoleUpdate"`
	PageRoleDelete    int32     `gorm:"column:PageRoleDelete;not null;default:false" json:"PageRoleDelete"`
	PageSettingCreate int32     `gorm:"column:PageSettingCreate;not null;default:false" json:"PageSettingCreate"`
	PageSettingRead   int32     `gorm:"column:PageSettingRead;not null;default:false" json:"PageSettingRead"`
	PageSettingUpdate int32     `gorm:"column:PageSettingUpdate;not null;default:false" json:"PageSettingUpdate"`
	PageSettingDelete int32     `gorm:"column:PageSettingDelete;not null;default:false" json:"PageSettingDelete"`
	PageAccountCreate int32     `gorm:"column:PageAccountCreate;not null;default:false" json:"PageAccountCreate"`
	PageAccountRead   int32     `gorm:"column:PageAccountRead;not null;default:false" json:"PageAccountRead"`
	PageAccountUpdate int32     `gorm:"column:PageAccountUpdate;not null;default:false" json:"PageAccountUpdate"`
	PageAccountDelete int32     `gorm:"column:PageAccountDelete;not null;default:false" json:"PageAccountDelete"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
